main: org.meekers.plugins.savemybuilding.SaveMyBuilding
name: SaveMyBuilding
version: 1.0
author: Jared Meeker
description: Save your creations and load them into a new world

commands:
   smb:
      description: Interface for saving your buildings
      usage: /<command> [ list | save | load ]